server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        root /etc/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    location /assets/ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }

    # Configuração de cache para assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2)$ {
        expires max;
        add_header Cache-Control "public, no-transform, max-age=31536000, immutable";
        try_files $uri =404;
    }

    # Configuração para arquivos de fonte do PrimeNG (se necessário)
    location ~* \.(ttf|otf|eot)$ {
        add_header Access-Control-Allow-Origin *;
        expires 1y;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /etc/nginx/html;
    }

    # Enable GZIP compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
