apiVersion: v1
kind: Service
metadata:
  name: calendar-fe
  namespace: calendar
spec:
  selector:
    app: calendar-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
